/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  document: [
    {
      // type: 'autogenerated',
      type: 'doc',
      id: 'document/intro',
    },
    {
      type: 'category',
      label: '快速入门',
      items: [
        {
          type: 'autogenerated',
          dirName: 'document/basic'
        }
      ]
    },
    {
      type: 'category',
      label: '进阶',
      items: [
        {
          type: 'autogenerated',
          dirName: 'document/advanced'
        }
      ]
    },
    {
      type: 'doc',
      id: 'document/plugin'
    }
  ],
  developer: [
    {
      type: 'autogenerated',
      // label: '开发',
      dirName: 'developer', // '.' 指的是当前的 docs 目录（也就是存放文档的根目录）
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
